### PR TITLE
Allow to pass null to addSpacer

### PR DESCRIPTION
**Pull request by jasperhartong**
Is used to create a flexible spacer.

PS: thanks for creating and updating these types! :)

### CODE REVIEW

**Comment by schl3ck** [comment]
Since I don't have iOS 14 to try it out:

Does it also work if you leave out the parameter alltogether in Scriptable? If yes, then I would go for that and make the parameter optional instead of requiring it to be explicitly `null`.

**Comment by jasperhartong** [comment]
Just tested it. If you pass in nothing it indeed defaults to the flexible behaviour, so `null`.

Thought it would default to 0, but I think I misread the docs here: https://docs.scriptable.app/listwidget/#spacing
```
Spacing: Specifies the spacing between elements in the widget. You can also use the addSpacer() function on the widget to add spacing between elements. Defaults to 0.
```

Anyway, making it optional is more clean then indeed.

**Comment by schl3ck** [comment]
Looks good!

Ah yes, that's a little confusing. The "thing" you linked to is probably the "global" spacing between items, but a spacer from `addSpacer` is completely seperate from the global spacing as far as I understood it.

Thank you for the contribution!

**Comment by schl3ck** [comment]
This change is also now on npm: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49437#issuecomment-724535229

**Pull request merged**
